dishes/urls.py
from django.urls import path
from dishes.views import index,book_table, about, menu, service,contact, team,\
    basket_add, basket_remove, purchase, thankYou, cs_thanks, testimonial, booking_thanks
app_name = 'dishes'
urlpatterns = [
    path('', index, name='index'),
    path('category/<int:category_id>/', index, name='category'),
    path('booktable', book_table, name = 'book_table'),
    path('menu', menu, name='menu'),
    path('menu/category/<int:category_id>/', menu, name='m_category'),
    path('about', about, name = 'about'),
    path('service', service, name='service'),
    path('contact', contact, name='contact'),
    path('team', team, name='team'),
    path('basket/add/<int:dish_id>/', basket_add, name='basket_add'),
    path('basket/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('order', purchase, name='order'),
    path('thanks', thankYou, name='thanks'),
    path('cs_thanks', cs_thanks, name='cs_thanks'),
    path('testimonial', testimonial, name='testimonial'),
    path('booking_thanks', booking_thanks, name='booking_thanks')


    ]

rest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from dishes.views import index


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', index, name='index'),
    path('dishes/', include('dishes.urls', namespace='dishes')),
    path('user/', include('user.urls', namespace='user'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path


from user.views import login, logout, register, profile, view_basket
app_name = 'user'
urlpatterns = [
    path('login',login, name='login'),
    path('logout', logout, name='logout'),
    path('register', register, name='register'),
    path('profile', profile, name='profile'),
    path('view_basket', view_basket, name='view_basket')

]

dishes/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.

class Category(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=128, unique=True)
    icon = models.CharField(null=True, max_length=128, unique=True)
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'



class Dish(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=128, unique=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='dishes_images')
    description = models.TextField(null=True, blank=True)
    category = models.ForeignKey(null=True, to=Category, on_delete=models.CASCADE)


    class Meta:
        verbose_name = 'Dish'
        verbose_name_plural = 'Dishes'

class Booking(models.Model):
    def __str__(self):
        return self.full_name
    full_name = models.CharField(max_length=128, unique=False)
    email = models.CharField(max_length=128)
    date = models.CharField(max_length=128)
    npeople = models.IntegerField()
    message = models.CharField(max_length=1000, blank=True)

    class Meta:
        verbose_name = 'booking'
        verbose_name_plural = 'bookings'

class CustomerSupport(models.Model):
    def __str__(self):
        return self.full_name

    full_name = models.CharField(max_length=128)
    email = models.CharField(max_length=128)
    subject = models.CharField(max_length=1000, blank=True)
    message = models.CharField(max_length=1000, blank=True)

    class Meta:
        verbose_name = 'csform'
        verbose_name_plural = 'csforms'


class Employee(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=128, unique=True)
    position = models.CharField(max_length=128, blank=True)
    image = models.ImageField(null=True, upload_to='employees_images')
    class Meta:
        verbose_name = 'employee'
        verbose_name_plural = 'employees'


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum()for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)

class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    dish = models.ForeignKey(to=Dish, on_delete = models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    create_timestamp = models.DateTimeField(auto_now_add=True)

    objects = BasketQuerySet.as_manager()

    def sum(self):
        return self.dish.price*self.quantity

class Order(models.Model):
    first_name = models.CharField(max_length=128, blank=True)
    last_name = models.CharField(max_length=128, blank=True)
    email = models.CharField(max_length=128, blank=True)
    credit_card = models.CharField(max_length=128, blank=True)
    address = models.CharField(max_length=128, blank=True)
    user = models.ForeignKey(null=True, to=User, on_delete=models.CASCADE)
    basket = models.CharField(max_length=1000, blank=True)
    total_price = models.IntegerField(max_length=1000,blank=True, null=True)


class Review(models.Model):
    full_name = models.CharField(max_length=128, blank=True)
    profession = models.CharField(max_length=128, blank=True)
    image = models.ImageField(upload_to='clients_images')
    review = models.CharField(max_length=128, blank=True)

dishes/forms.py
from django import forms
from dishes.models import Booking, CustomerSupport, Order

class BookingForm(forms.Form):
    full_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', "placeholder": 'Your Name',

    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control', "placeholder": 'Your Email'
    }))
    date = forms.CharField(widget=forms.DateTimeInput(attrs={
        'class': 'form-control datetimepicker-input', "placeholder": 'Data & Time',
        'data-target': '#date3',
        'data-toggle': 'datetimepicker'
    }))
    npeople = forms.IntegerField(widget=forms.TextInput(attrs={
        'class': 'form-control', "placeholder": 'Number of People'
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control', "placeholder": 'Special Request',

    }))

    class Meta:
        model = Booking
        fields = ('full_name', 'email', 'date', 'npeople', 'message')

class CustomerSupportForm(forms.Form):
    full_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', "placeholder": 'Your Name',

    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control', "placeholder": 'Your Email'
    }))
    subject = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', "placeholder": 'Subject'
    }))
    message = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control', "placeholder": 'Leave a message here',
    }))

    class Meta:
        model = CustomerSupport
        fields = ('full_name', 'email', 'subject', 'message')

class OrderForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', "placeholder": 'First Name',

    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', "placeholder": 'Last Name',

    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control', "placeholder": 'Your Email'
    }))

    credit_card = forms.IntegerField(widget=forms.TextInput(attrs={
        'class': 'form-control', "placeholder": 'Credit Card Number'
    }))
    address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', "placeholder": 'Your Address'
    }))
    user = forms.CharField(widget=forms.HiddenInput(attrs={
        'class': 'form-control', "placeholder": 'User',


    }))
    basket = forms.CharField(widget=forms.HiddenInput(attrs={
        'class': 'form-control', "placeholder": 'Basket',

    }))
    total_price = forms.IntegerField(widget=forms.HiddenInput(attrs={
        'class': 'form-control', "placeholder": 'Total Price'
    }))


    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'email', 'credit_card', 'address', 'user', 'basket','total_price')

dishes/views.py
from django.shortcuts import render
from dishes.models import Dish, Booking, Category, CustomerSupport, Employee, Basket, Order, Review
from django.http import HttpResponseRedirect
from dishes.forms import BookingForm, CustomerSupportForm, OrderForm
from django.contrib.auth.decorators import login_required

def index(request, category_id=None):

    dishes = Dish.objects.all()
    if category_id:
        dishes = dishes.filter(category_id=category_id)
    categories = Category.objects.all()
    team = Employee.objects.all()
    reviews = Review.objects.all()
    context = {'title': 'Restaurant',
               'form': BookingForm(), 'dishes': dishes, 'categories': categories, 'cat_id':category_id, 'team':team,'reviews':reviews}
    return render(request, 'dishes/index.html',context)
# Create your views here.

def menu(request, category_id=None):
    dishes = Dish.objects.all()
    if category_id:
        dishes = dishes.filter(category_id=category_id)
    categories = Category.objects.all()

    context = {'title': 'Menu',
               'dishes':dishes, 'categories': categories, 'cat_id':category_id}
    return render(request, 'dishes/menu.html', context)

def book_table(request):
    if request.method=='POST':
        form = BookingForm(data=request.POST)
        if form.is_valid():
            full_name = request.POST['full_name']
            email = request.POST['email']
            date = request.POST['date']
            npeople = request.POST['npeople']
            message = request.POST['message']
            booking = Booking(full_name=full_name, email=email,
                                  date=date, npeople=npeople, message=message)
            booking.save()
            request.session['booking_data']={'full_name': booking.full_name, 'email': booking.email, 'date':booking.date, 'npeople': booking.npeople, 'message': booking.message}
            return HttpResponseRedirect('booking_thanks')
    else:
        form = BookingForm()
    context = {'form':form}
    return render(request, 'dishes/booking.html', context)



def about(request):
    team = Employee.objects.all()
    context = {'title': 'About', 'team': team}
    return render(request, 'dishes/about.html', context)

def service(request):
    context = {'title':'Service'}
    return render(request, 'dishes/service.html', context)



def contact(request):
    if request.method=='POST':
        form =CustomerSupportForm(data=request.POST)
        if form.is_valid():
            full_name = request.POST['full_name']
            email = request.POST['email']
            subject = request.POST['subject']
            message = request.POST['message']
            cscontact = CustomerSupport(full_name=full_name, email=email, subject=subject, message=message)
            cscontact.save()
            request.session['data']={'full_name': cscontact.full_name,
                                     'email': cscontact.email,
                                     'subject': cscontact.subject,
                                     'message':cscontact.message}
            return HttpResponseRedirect('cs_thanks')
    else:
        form = CustomerSupportForm()
    context = {'form':form}
    return render(request, 'dishes/contact.html', context)


def team(request):
    employees = Employee.objects.all()
    context = {'title': 'Team', 'team':employees}
    return render(request, 'dishes/team.html', context)
@login_required
def basket_add(request, dish_id):
    dish = Dish.objects.get(id=dish_id)
    baskets = Basket.objects.filter(user=request.user, dish=dish)

    if not baskets.exists():
        Basket.objects.create(user=request.user, dish=dish, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity +=1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])


def purchase(request):
    user = request.user
    basket = Basket.objects.filter(user=request.user)
    string = ""
    total_sum = 0

    for b in basket:
        string += f"{b.quantity} {b.dish.name} (s)\n"
        total_sum += b.sum()
    if request.method=='POST':
        form = OrderForm(data=request.POST)
        if form.is_valid():
            first_name = request.POST['first_name']
            last_name = request.POST['last_name']
            email = request.POST['email']
            credit_card = request.POST['credit_card']
            address = request.POST['address']
            order = Order(first_name=first_name,
                          last_name=last_name,
                          email=email, credit_card=credit_card,
                          address=address, user=user, basket = string,total_price=total_sum)


            order.save()
            return HttpResponseRedirect('thanks')
    else:
        form = OrderForm(initial={'user':user, 'basket':basket, 'total_price':total_sum})

    basket = Basket.objects.filter(user=request.user)

    context = {'title': 'Checkout', 'form':form, 'basket':basket}
    return render(request, 'dishes/order.html',context)

def thankYou(request):
    basket = Basket.objects.filter(user=request.user)
    context = {'title': 'Thank You!', 'basket': basket}
    return render(request, 'dishes/thanks.html', context)

def cs_thanks(request):
    data = request.session['data']
    context = {'title': 'Customer Support', 'message': data}
    return render(request, 'dishes/cs_thanks.html', context)

def testimonial(request):
    reviews = Review.objects.all()
    context = {'title': 'Testimonial', 'reviews': reviews}
    return render(request, 'dishes/testimonial.html', context)

def booking_thanks(request):
    data = request.session['booking_data']
    context = {'title':'Booking', 'message': data}
    return render(request, 'dishes/booking_thanks.html', context)

dishes/templates/dishes/menu.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Restoran - Bootstrap Restaurant Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="/static/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&family=Pacifico&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="/static/lib/animate/animate.min.css" rel="stylesheet">
    <link href="/static/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="/static/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="/static/css/style.css" rel="stylesheet">
    <style>
    #view-cart-btn {
        position: fixed;
        bottom: 20px;
        right: 20px;
    }
</style>
</head>

<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->


        <!-- Navbar & Hero Start -->
        <div class="container-xxl position-relative p-0">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
                <a href="{% url 'dishes:index'%}" class="navbar-brand p-0">
                    <h1 class="text-primary m-0"><i class="fa fa-utensils me-3"></i>At Begimai's</h1>
                    <!-- <img src="img/logo.png" alt="Logo"> -->
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto py-0 pe-4">
                        <a href="{%url 'dishes:index'%}" class="nav-item nav-link">Home</a>
                        <a href="{% url 'dishes:about'%}" class="nav-item nav-link">About</a>
                        <a href="{% url 'dishes:service'%}" class="nav-item nav-link">Service</a>
                        <a href="{% url 'dishes:menu'%}" class="nav-item nav-link active">Menu</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                            <div class="dropdown-menu m-0">
                                <a href="{% url 'dishes:book_table'%}" class="dropdown-item">Booking</a>
                                <a href="{% url 'dishes:team'%}" class="dropdown-item">Our Team</a>
                                <a href="{% url 'dishes:testimonial'%}" class="dropdown-item">Testimonial</a>
                                {% if user.is_authenticated %}
                                <a href="{% url 'user:logout'%}" class="dropdown-item">Logout</a>
                                <a href="{% url 'user:profile'%}" class="dropdown-item">Profile</a>

                                <a href="{% url 'user:view_basket'%}" class="dropdown-item">View Basket</a>

                                {% else %}
                                <a href="{% url 'user:login' %}" class="dropdown-item">Login</a>
                                {%endif%}
                                <a href="{% url 'admin:index'%}" class="dropdown-item">Admin Panel</a>
                            </div>
                        </div>
                        <a href="{% url 'dishes:contact'%}" class="nav-item nav-link">Contact</a>
                    </div>
                    <a href="{% url 'dishes:book_table'%}" class="btn btn-primary py-2 px-4">Book A Table</a>
                </div>
            </nav>

            <div class="container-xxl py-5 bg-dark hero-header mb-5">
                <div class="container text-center my-5 pt-5 pb-4">
                    <h1 class="display-3 text-white mb-3 animated slideInDown">Food Menu</h1>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb justify-content-center text-uppercase">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item"><a href="#">Pages</a></li>
                            <li class="breadcrumb-item text-white active" aria-current="page">Menu</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
        <!-- Navbar & Hero End -->


        <!-- Menu Start -->
        <div class="container-xxl py-5">
            <div class="container">
                <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
                    <h5 class="section-title ff-secondary text-center text-primary fw-normal">Food Menu</h5>
                    <h1 class="mb-5">Most Popular Items</h1>
                </div>
                <div class="tab-class text-center wow fadeInUp" data-wow-delay="0.1s">
                    <ul class="nav nav-pills d-inline-flex justify-content-center border-bottom mb-5">

                        {%for category in categories%}


                        <li class="nav-item">
                            <a class="nav-link {% if category.id == cat_id %}active{% endif %}" href="{% url 'dishes:m_category' category.id %}">
                                <div class="icon-wrapper">
                                <i class="{{ category.icon }}"></i>
                                    <h6 class="mt-n1 mb-0">{{category.name}}</h6>
                                </div>
                            </a>
                        </li>
                        {%endfor%}


                    </ul>
                     <div class="tab-content">
                <div id="{category.id}" class="tab-pane fade show p-0 active">
                    <div class="row g-4">
                        {% for dish in dishes %}
                        <div class="col-lg-6">
                            <div class="d-flex align-items-center">
                                <img class="flex-shrink-0 img-fluid rounded" src="{{ dish.image.url }}" alt="" style="width: 80px;">
                                <div class="w-100 d-flex flex-column text-start ps-4">
                                    <h5 class="d-flex justify-content-between border-bottom pb-2">
                                        <span>{{ dish.name }}</span>
                                        <span class="text-primary">${{ dish.price }}</span>
                                    </h5>
                                    <div class="d-flex justify-content-between align-items-center">
                                        <small class="fst-italic">{{ dish.description }}</small>

                                        <a class="btn btn-sm btn-primary" href="{% url 'dishes:basket_add' dish.id %}">
                                            Add to Cart

                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
                </div>
            </div>
        </div>
        <!-- Menu End -->
        

        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Company</h4>
                        <a class="btn btn-link" href="">About Us</a>
                        <a class="btn btn-link" href="">Contact Us</a>
                        <a class="btn btn-link" href="">Reservation</a>
                        <a class="btn btn-link" href="">Privacy Policy</a>
                        <a class="btn btn-link" href="">Terms & Condition</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Contact</h4>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Opening</h4>
                        <h5 class="text-light fw-normal">Monday - Saturday</h5>
                        <p>09AM - 09PM</p>
                        <h5 class="text-light fw-normal">Sunday</h5>
                        <p>10AM - 08PM</p>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Newsletter</h4>
                        <p>Sign up for updates</p>
                        <div class="position-relative mx-auto" style="max-width: 400px;">
                            <input class="form-control border-primary w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                            <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">At Begimai's</a>, All Right Reserved.
							
							<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
							Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="{%url 'dishes:index'%}">Home</a>
                                <a href="">Cookies</a>
                                <a href="">Help</a>
                                <a href="">FQAs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/static/lib/wow/wow.min.js"></script>
    <script src="/static/lib/easing/easing.min.js"></script>
    <script src="/static/lib/waypoints/waypoints.min.js"></script>
    <script src="/static/lib/counterup/counterup.min.js"></script>
    <script src="/static/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="/static/lib/tempusdominus/js/moment.min.js"></script>
    <script src="/static/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="/static/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="/static/js/main.js"></script>
</body>

</html>