dishes/urls.py
from django.urls import path
from dishes.views import index,book_table, about, menu, service,contact, team,\
    basket_add, basket_remove, purchase, thankYou, cs_thanks, testimonial, booking_thanks
app_name = 'dishes'
urlpatterns = [
    path('', index, name='index'),
    path('category/<int:category_id>/', index, name='category'),
    path('booktable', book_table, name = 'book_table'),
    path('menu', menu, name='menu'),
    path('menu/category/<int:category_id>/', menu, name='m_category'),
    path('about', about, name = 'about'),
    path('service', service, name='service'),
    path('contact', contact, name='contact'),
    path('team', team, name='team'),
    path('basket/add/<int:dish_id>/', basket_add, name='basket_add'),
    path('basket/remove/<int:basket_id>/', basket_remove, name='basket_remove'),
    path('order', purchase, name='order'),
    path('thanks', thankYou, name='thanks'),
    path('cs_thanks', cs_thanks, name='cs_thanks'),
    path('testimonial', testimonial, name='testimonial'),
    path('booking_thanks', booking_thanks, name='booking_thanks')


    ]

rest/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from dishes.views import index


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', index, name='index'),
    path('dishes/', include('dishes.urls', namespace='dishes')),
    path('user/', include('user.urls', namespace='user'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path


from user.views import login, logout, register, profile, view_basket
app_name = 'user'
urlpatterns = [
    path('login',login, name='login'),
    path('logout', logout, name='logout'),
    path('register', register, name='register'),
    path('profile', profile, name='profile'),
    path('view_basket', view_basket, name='view_basket')

]

user/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.

user/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from django.contrib.auth.models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Enter your username'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Enter your password'
    }))
    class Meta:
        model = User
        fields = ('username', 'password')

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Enter your name'
    }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control ', 'placeholder': 'Enter your last name'
    }))

    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control', 'placeholder': 'Enter your username'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'form-control', 'placeholder': 'Enter your email'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Enter your password'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control', 'placeholder': 'Confirm password'
    }))
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control py-4'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control py-4'}))

    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'readonly':True}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control', 'readonly':True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

user/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse
from user.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from dishes.models import Basket

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST) # data from request variable
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                return HttpResponseRedirect(reverse('index'))

    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'user/login.html',context)
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data = request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Congratulations! You've successfully registered")
            return HttpResponseRedirect(reverse('user:login'))
    else:

        form = UserRegistrationForm()
    context = {'form':form}
    return render(request, 'user/register.html',context)


def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance = request.user, data = request.POST, files = request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('user:profile'))
        else:
            print(form.errors)
    else:
        form = UserProfileForm(instance = request.user)

    context = {'title': 'Profile', 'form': form, 'baskets': Basket.objects.filter(user=request.user)}
    return render(request, 'user/profile.html', context)
# Create your views here.
def view_basket(request):
    baskets = Basket.objects.filter(user=request.user)
    context = {'title': 'Basket', 'baskets':baskets}
    return render(request, 'dishes/basket.html', context)

user/templates/user/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Login - Restoran</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="/static/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&family=Pacifico&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="/static/css/style.css" rel="stylesheet">
    <style>

        .container-xxl {
            height: 100vh;

        }
        .card {
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
        }

    </style>
</head>

<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->

        <!-- Login Form Start -->
        <div class="container-xxl position-relative p-0">
            <div class="container py-5">
                <div class="row justify-content-center">
                    <div class="col-md-6">
                        {% if messages or form.non_field_errors %}

                            <div class="alert alert
                            {%if messages%} alert-success {%else%} alert-warning {%endif%}
                            alert-dismissible fade show" role="alert"
                                style="margin-top: 50px;">
                                {% if messages%}
                                    {%for message in messages%}
                                        {{message}}
                                    {%endfor%}
                                {%else%}

                                    {{form.non_field_errors}}
                                {%endif%}

                                </div>
                        {% endif %}
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title text-center">Login</h5>
                                <form action="{% url 'user:login'%}"method="post">
                                    {%csrf_token%}
                                    <div class="mb-3">
                                        <label for="{{form.username.id_for_label}}" class="form-label">Username</label>
                                        {{form.username}}

                                    </div>
                                    <div class="mb-3">
                                        <label for="{{form.password.id_for_label}}" class="form-label">Password</label>
                                        {{form.password}}

                                    </div>
                                    <button type="submit" class="btn btn-primary w-100">Login</button>
                                </form>
                            </div>
                        </div>
                    <div class="text-center mt-3">
                        <p>Don't have an account? <a href="{%url 'user:register'%}"> Sign Up </a></p>
                </div>
            </div>
           </div>
          </div>

        </div>
        <!-- Login Form End -->

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="/static/lib/wow/wow.min.js"></script>
        <script src="/static/lib/easing/easing.min.js"></script>
        <script src="/static/lib/waypoints/waypoints.min.js"></script>
        <script src="/static/lib/counterup/counterup.min.js"></script>
        <script src="/static/lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="/static/lib/tempusdominus/js/moment.min.js"></script>
        <script src="/static/lib/tempusdominus/js/moment-timezone.min.js"></script>
        <script src="/static/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

        <!-- Template Javascript -->
        <script src="/static/js/main.js"></script>
    </div>
</body>

</html>

user/templates/user/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Begimai - Bootstrap Restaurant Template</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="/static/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&family=Pacifico&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="/static/lib/animate/animate.min.css" rel="stylesheet">
    <link href="/static/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="/static/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="/static/css/style.css" rel="stylesheet">
</head>

<body>
    <div class="container-xxl bg-white p-0">



        <!-- Navbar & Hero Start -->
        <div class="container-xxl position-relative p-0">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-4 px-lg-5 py-3 py-lg-0">
                <a href="" class="navbar-brand p-0">
                    <h1 class="text-primary m-0"><i class="fa fa-utensils me-3"></i>At Begimai's</h1>
                    <!-- <img src="img/logo.png" alt="Logo"> -->
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="fa fa-bars"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav ms-auto py-0 pe-4">
                        <a href="{% url 'dishes:index'%}" class="nav-item nav-link active">Home</a>
                        <a href="{% url 'dishes:about'%}" class="nav-item nav-link">About</a>
                        <a href="{% url 'dishes:service'%}" class="nav-item nav-link">Service</a>
                        <a href="{% url 'dishes:menu'%}" class="nav-item nav-link">Menu</a>
                        <div class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
                            <div class="dropdown-menu m-0">
                                <a href="{% url 'dishes:book_table'%}" class="dropdown-item">Booking</a>
                                <a href="{%url 'dishes:team'%}" class="dropdown-item">Our Team</a>
                                <a href="/static/testimonial.html" class="dropdown-item">Testimonial</a>
                                {% if user.is_authenticated %}
                                <a href="{% url 'user:logout'%}" class="dropdown-item">Logout</a>
                                {% else %}
                                <a href="{% url 'user:login' %}" class="dropdown-item">Login</a>
                                {%endif%}
                                <a href="{% url 'admin:index'%}" class="dropdown-item">Admin Panel</a>

                            </div>
                        </div>
                        <a href="{% url 'dishes:contact' %}" class="nav-item nav-link">Contact</a>
                    </div>
                    <a href="" class="btn btn-primary py-2 px-4">Book A Table</a>
                </div>
            </nav>

            <div class="container-xxl py-5 bg-dark hero-header mb-5">
                <div class="container my-5 py-5">
                     <div class="row">
            <div class="col-lg-7 mx-auto">
                <h4 class="mt-3 mb-3 text-primary">Profile</h4>

                <form action="{% url 'user:profile' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="small mb-1 text-primary" for="{{form.first_name.id_for_label}}">First Name</label>
                        {{ form.first_name }}
                    </div>
                    <div class="form-group">
                        <label class="small mb-1 text-primary" for="{{form.last_name.id_for_label}}">Last Name</label>
                        {{ form.last_name }}
                    </div>
                    <div class="form-group">
                        <label class="small mb-1 text-primary" for="{{form.username.id_for_label}}">Username</label>
                        {{ form.username }}
                    </div>
                    <div class="form-group">
                        <label class="small mb-1 text-primary" for="{{form.email.id_for_label}}">Email</label>
                        {{ form.email }}
                    </div>
                    <div class="form-group mt-4">
                        <input class="btn btn-primary btn-block" type="submit" value="Save">
                    </div>
                </form>
            </div>

        </div>
    </div>
                </div>
            </div>
        </div>










        <!-- Footer Start -->
        <div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
            <div class="container py-5">
                <div class="row g-5">
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Company</h4>
                        <a class="btn btn-link" href="">About Us</a>
                        <a class="btn btn-link" href="">Contact Us</a>
                        <a class="btn btn-link" href="">Reservation</a>
                        <a class="btn btn-link" href="">Privacy Policy</a>
                        <a class="btn btn-link" href="">Terms & Condition</a>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Contact</h4>
                        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
                        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                        <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
                        <div class="d-flex pt-2">
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                            <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Opening</h4>
                        <h5 class="text-light fw-normal">Monday - Saturday</h5>
                        <p>09AM - 09PM</p>
                        <h5 class="text-light fw-normal">Sunday</h5>
                        <p>10AM - 08PM</p>
                    </div>
                    <div class="col-lg-3 col-md-6">
                        <h4 class="section-title ff-secondary text-start text-primary fw-normal mb-4">Newsletter</h4>
                        <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
                        <div class="position-relative mx-auto" style="max-width: 400px;">
                            <input class="form-control border-primary w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                            <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container">
                <div class="copyright">
                    <div class="row">
                        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                            &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

							<!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
							Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
                        </div>
                        <div class="col-md-6 text-center text-md-end">
                            <div class="footer-menu">
                                <a href="">Home</a>
                                <a href="">Cookies</a>
                                <a href="">Help</a>
                                <a href="">FQAs</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End -->


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/static/lib/wow/wow.min.js"></script>
    <script src="/static/lib/easing/easing.min.js"></script>
    <script src="/static/lib/waypoints/waypoints.min.js"></script>
    <script src="/static/lib/counterup/counterup.min.js"></script>
    <script src="/static/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="/static/lib/tempusdominus/js/moment.min.js"></script>
    <script src="/static/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="/static/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="/static/js/main.js"></script>
</body>

</html>

user/templates/user/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Register - Restoran</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="/static/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Nunito:wght@600;700;800&family=Pacifico&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="/static/css/style.css" rel="stylesheet">
    <style>
        .container-xxl {
        height: 100vh;
        }
        .card {
        height: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
        }
        .register-button {
        margin-top: 20px;
        }
    </style>
</head>

<body>
    <div class="container-xxl bg-white p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->

        <!-- Registration Form Start -->
        <div class="container-xxl position-relative p-0">
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-center">Register</h5>
                        <form action="{% url 'user:register'%}" method="post">
                            {% csrf_token %}
                            <div class="container">
                                <div class="row mb-3">
                                    <div class="col-md-6">
                                        <label for="{{ form.first_name.id_for_label }}" class="form-label">First Name</label>
                                        {{ form.first_name }}
                                    </div>
                                    <div class="col-md-6">
                                        <label for="{{ form.last_name.id_for_label }}" class="form-label">Last Name</label>
                                        {{ form.last_name }}
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-md-6">
                                        <label for="{{ form.username.id_for_label }}" class="form-label">Username</label>
                                        {{ form.username }}
                                    </div>
                                    <div class="col-md-6">
                                        <label for="{{ form.email.id_for_label }}" class="form-label">Email</label>
                                        {{ form.email }}
                                    </div>
                                </div>
                                <div class="row mb-3">
                                    <div class="col-md-6">
                                        <label for="{{ form.password1.id_for_label }}" class="form-label">Password</label>
                                        {{ form.password1 }}
                                    </div>
                                    <div class="col-md-6">
                                        <label for="{{ form.password1.id_for_label }}" class="form-label">Confirm Password</label>
                                        {{ form.password2 }}
                                    </div>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary w-100 register-button">Register</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




        <!-- Registration Form End -->

        <!-- JavaScript Libraries -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
        <script src="/static/lib/wow/wow.min.js"></script>
        <script src="/static/lib/easing/easing.min.js"></script>
        <script src="/static/lib/waypoints/waypoints.min.js"></script>
        <script src="/static/lib/counterup/counterup.min.js"></script>
        <script src="/static/lib/owlcarousel/owl.carousel.min.js"></script>
        <script src="/static/lib/tempusdominus/js/moment.min.js"></script>
        <script src="/static/lib/tempusdominus/js/moment-timezone.min.js"></script>
        <script src="/static/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

        <!-- Template Javascript -->
        <script src="/static/js/main.js"></script>
    </div>
</body>

</html>